Proyecto/Models/UsuarioRol.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto.Models
{
    public class UsuarioRol
    {
        public int IdUsuarioRol { get; set; }
        public int IdUsuario { get; set; }
        public int IdRol { get; set; }



    }
}

Proyecto/Controllers/UsuarioRolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using BLL;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    [Authorize]
    public class UsuarioRolController : Controller
    {
    clsBitacora Objbitacora = new clsBitacora();
    [Authorize(Roles = "Administrador")]
    public ActionResult Index()
        {
            try
            {
                List<UsuarioRolList> listaRol = new List<UsuarioRolList>();
                clsUsuarioRol UsuarioRol = new clsUsuarioRol();
                var data = UsuarioRol.ConsultarUsuarioRolLista().ToList();

                foreach (var item in data)
                {
                    UsuarioRolList modelo = new UsuarioRolList();
                    modelo.Id = item.Id;
                    modelo.Nombre = item.Nombre;
                    modelo.Rol = item.Rol;
                    listaRol.Add(modelo);
                }
                return View(listaRol);
            }
            catch
            {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("UsuarioRolController", "Index", "Eror en la consulta de los datos", 1, DateTime.UtcNow.Date, us);

        return RedirectToAction("Error", "Error");
            }
        }
    [Authorize(Roles = "Administrador")]
    public ActionResult Crear()
        {
            try
            {

                ViewBag.ListaUsuario = CargarUsuario();
                ViewBag.ListaRol = CargarRol();

                return View();
            }
            catch (Exception)
            {

                throw;
            }

        }


    [Authorize(Roles = "Administrador")]
    [HttpPost]
        public ActionResult Crear(UsuarioRol usuarioRol)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    clsUsuarioRol UsuarioRol = new clsUsuarioRol();
                    bool Resultado = UsuarioRol.AgregarUsuarioRol(usuarioRol.IdUsuario, usuarioRol.IdRol);
                    clsBitacora Objbitacora = new clsBitacora();

                    if (Resultado)
                    {
            int us = Convert.ToInt32(Session["IdUsuario"].ToString());
            Objbitacora.AgregarBitacora("UsuarioRolController", "Crear", "Exito", 1, DateTime.UtcNow.Date, us);

            return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.ListaUsuario = CargarUsuario();
                        ViewBag.ListaRol = CargarRol();

                        return View("Crear");
                    }
                }
                else
                {
                    ViewBag.ListaUsuario = CargarUsuario();
                    ViewBag.ListaRol = CargarRol();

                    return View("Crear");
                }

            }
            catch
            {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("UsuarioRolController", "Crear", "Error en creacion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
            }
        }
    [Authorize(Roles = "Administrador")]
    public ActionResult Editar(int id)
        {
            try
            {
        ViewBag.ListaUsuario = CargarUsuario();
        ViewBag.ListaRol = CargarRol();

        clsUsuarioRol UsuarioRol = new clsUsuarioRol();

                var dato = UsuarioRol.ConsultaUsuarioRol(id);
                UsuarioRol modelo = new UsuarioRol();
                modelo.IdUsuarioRol = dato.Id;
                modelo.IdUsuario = dato.IdUsuario;
                modelo.IdRol = dato.IdRol;
                return View(modelo);
            }
            catch (Exception)
            {

                throw;
            }

        }
    [Authorize(Roles = "Administrador")]
    [HttpPost]
        public ActionResult Editar(int id, UsuarioRol usuarioRol)
        {
            try
            {
                clsUsuarioRol UsuarioRol = new clsUsuarioRol();
                bool Resultado = UsuarioRol.ActualizarUsuarioRol(id, usuarioRol.IdUsuario, usuarioRol.IdRol);

                if (Resultado)
                {
          int us = Convert.ToInt32(Session["IdUsuario"].ToString());
          Objbitacora.AgregarBitacora("UsuarioRolController", "Editar", "Exito", 1, DateTime.UtcNow.Date, us);

          return RedirectToAction("Index");
                }
                else
                {

                    ViewBag.ListaUsuario = CargarUsuario();
                    ViewBag.ListaRol = CargarRol();
                    return View("Editar");
                }
            }
            catch
            {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("UsuarioRolController", "Editar", "Error en la edicion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
            }
        }
    [Authorize(Roles = "Administrador")]
    public ActionResult Eliminar(int id)
        {
            try
            {
                clsUsuarioRol UsuarioRol = new clsUsuarioRol();
                bool Resultado = UsuarioRol.EliminarUsuarioRol(id);

                if (Resultado)
                {
          int us = Convert.ToInt32(Session["IdUsuario"].ToString());
          Objbitacora.AgregarBitacora("UsuarioRolController", "Eliminar", "Exito", 1, DateTime.UtcNow.Date, us);

          return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch
            {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("UsuarioRolController", "Eliminar", "Error en la eliminacion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
            }
        }
        clsUsuario Usuario = new clsUsuario();
        public List<ConsultarUsuarioViewBagResult> CargarUsuario()
        {
            List<ConsultarUsuarioViewBagResult> usuario = Usuario.ConsultarUsuarioViewBag();
            return usuario;
        }
        clsRol Rol = new clsRol();
        public List<ConsultarRolResult> CargarRol()
        {
            List<ConsultarRolResult> rol = Rol.ConsultarRol();
            return rol;
        }
    }
}

Proyecto/Views/UsuarioRol/Crear.cshtml
@model Proyecto.Models.UsuarioRol

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crear</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
  <div class="form-horizontal">
    <h4>UsuarioRol</h4>
    <hr />
    @Html.Hidden("IdUsuarioRol", 0)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
      @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.IdUsuario, new SelectList(ViewBag.ListaUsuario, "IdUsuario", "Nombre"), "--Usuario--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 1 })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.IdRol, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.IdRol, new SelectList(ViewBag.ListaRol, "IdRol", "Descripcion"), "--Rol--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 2 })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Crear" class="btn btn-default" />
      </div>
    </div>
  </div>
    }
    
    <div>
        @Html.ActionLink("Regresar", "Index")
    </div>
</body>
</html>

Proyecto/Views/UsuarioRol/Editar.cshtml
@model Proyecto.Models.UsuarioRol

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
  <div class="form-horizontal">
    <h4>UsuarioRol</h4>
    <hr />
    @Html.HiddenFor(model => model.IdUsuarioRol)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
      @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.IdUsuario, new SelectList(ViewBag.ListaUsuario, "IdUsuario", "Nombre"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 1 })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.IdRol, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.IdRol, new SelectList(ViewBag.ListaRol, "IdRol", "Descripcion"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 2 })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Guardar" class="btn btn-default" />
      </div>
    </div>
  </div>
    }
    
    <div>
        @Html.ActionLink("Salir", "Index")
    </div>
</body>
</html>

Proyecto/Views/UsuarioRol/Index.cshtml
@model IEnumerable<Proyecto.Models.UsuarioRolList>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Nuevo UsuarioRol", "Crear", "UsuarioRol", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-small btn-primary pull-left" })
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rol)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rol)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }, new { @class = "btn btn-success btn-sm" }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id }, new { @class = "btn btn-danger btn-sm", onclick = "return Confirmar(this);" })
            </td>
        </tr>
    }
    </table>
</body>
</html>