Proyecto/Models/TipoIdentificacion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto.Models
{
  public class TipoIdentificacion
  {
    public int IdTipoIdentificacion { get; set; }
    public string Descripcion { get; set; }
    public bool Estado { get; set; }
  }
}

Proyecto/Controllers/TipoIdentificacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using BLL;
using Proyecto.Models;

namespace Proyecto.Controllers
{
  public class TipoIdentificacionController : Controller
  {
    clsBitacora Objbitacora = new clsBitacora();
    [Authorize(Roles = "Administrador")]
      public ActionResult Index()
      {
        try
        {
          List<TipoIdentificacion> listaTipoIdentificacion = new List<TipoIdentificacion>();
          clsTipoIdentificacion TipoIdentificacion = new clsTipoIdentificacion();
          var data = TipoIdentificacion.ConsultarTipoIdentificacion().ToList();

          foreach (var item in data)
          {
            TipoIdentificacion modelo = new TipoIdentificacion();
            modelo.IdTipoIdentificacion = item.IdTipoIdentificacion;
            modelo.Descripcion = item.Descripcion;
            modelo.Estado = item.Estado;
            listaTipoIdentificacion.Add(modelo);
          }
          return View(listaTipoIdentificacion);
        }
        catch
        {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("TipoIdentificacionController", "Index", "Eror en la consulta de los datos", 1, DateTime.UtcNow.Date, us);

        return RedirectToAction("Error", "Error");
        }
      }
      [Authorize(Roles = "Administrador")]
      public ActionResult Crear()
      {
        try
        {
          ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
          return View();
        }
        catch (Exception)
        {

          throw;
        }

      }


      [Authorize(Roles = "Administrador")]
      [HttpPost]
      public ActionResult Crear(TipoIdentificacion tipoIdentificacion)
      {
        try
        {
          if (ModelState.IsValid)
          {

            clsTipoIdentificacion TipoIdentificacion = new clsTipoIdentificacion();
            bool Resultado = TipoIdentificacion.AgregarTipoIdentificacion(tipoIdentificacion.Descripcion, tipoIdentificacion.Estado);
            clsBitacora Objbitacora = new clsBitacora();

            if (Resultado)
            {
            int us = Convert.ToInt32(Session["IdUsuario"].ToString());
            Objbitacora.AgregarBitacora("TipoIdentificacionController", "Crear", "Exito", 1, DateTime.UtcNow.Date, us);

            return RedirectToAction("Index");
            }
            else
            {
              ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
              return View("Crear");
            }
          }
          else
          {
            ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
            return View("Crear");
          }


        }
        catch
        {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("TipoIdentificacionController", "Crear", "Error en creacion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
        }
      }
      [Authorize(Roles = "Administrador")]
      public ActionResult Editar(int id)
      {
        try
        {
          clsTipoIdentificacion TipoIdentificacion = new clsTipoIdentificacion();
        ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
        var dato = TipoIdentificacion.ConsultaTipoIdentificacion(id);

          TipoIdentificacion modelo = new TipoIdentificacion();
          modelo.IdTipoIdentificacion = dato.IdTipoIdentificacion;
          modelo.Descripcion = dato.Descripcion;
          modelo.Estado = dato.Estado;
          return View(modelo);
        }
        catch (Exception)
        {

          throw;
        }

      }
      [Authorize(Roles = "Administrador")]
      [HttpPost]
      public ActionResult Editar(int id, TipoIdentificacion tipoIdentificacion)
      {
        try
        {
          clsTipoIdentificacion TipoIdentificacion = new clsTipoIdentificacion();
          bool Resultado = TipoIdentificacion.ActualizarTipoIdentificacion(id, tipoIdentificacion.Descripcion, tipoIdentificacion.Estado);

          if (Resultado)
          {
          int us = Convert.ToInt32(Session["IdUsuario"].ToString());
          Objbitacora.AgregarBitacora("TipoIdentificacionController", "Editar", "Exito", 1, DateTime.UtcNow.Date, us);

          return RedirectToAction("Index");
          }
          else
          {
            ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
            return View("Editar");
          }
        }
        catch
        {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("TipoIdentificacionController", "Editar", "Error en la edicion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
        }
      }
      [Authorize(Roles = "Administrador")]
      public ActionResult Eliminar(int id)
      {
        try
        {
          clsTipoIdentificacion TipoIdentificacion = new clsTipoIdentificacion();
          bool Resultado = TipoIdentificacion.EliminarTipoIdentificacion(id);

          if (Resultado)
          {
          int us = Convert.ToInt32(Session["IdUsuario"].ToString());
          Objbitacora.AgregarBitacora("TipoIdentificacionController", "Eliminar", "Exito", 1, DateTime.UtcNow.Date, us);

          return RedirectToAction("Index");
          }
          else
          {
            return RedirectToAction("Index");
          }

        }
        catch
        {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("TipoIdentificacionController", "Eliminar", "Error en la eliminacion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
        }
      }
    }
  }

Proyecto/Views/TipoIdentificacion/Crear.cshtml
@model Proyecto.Models.TipoIdentificacion

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>Crear</title>
</head>
<body>
  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/jqueryval")


  @using (Html.BeginForm())
  {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <h4>TipoIdentificacion</h4>
      <hr />
      @Html.Hidden("IdTipoIdentificacion", 0)
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger", tabindex = 1})
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          <div class="checkbox">
            @Html.DropDownListFor(model => model.Estado, new SelectList(ViewBag.ListaEstados, "Value", "Text"), "--Estado--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 2 })
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <input type="submit" value="Crear" class="btn btn-default" />
        </div>
      </div>
    </div>
  }

  <div>
    @Html.ActionLink("Salir", "Index")
  </div>
</body>
</html>

Proyecto/Views/TipoIdentificacion/Editar.cshtml
@model Proyecto.Models.TipoIdentificacion

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>Editar</title>
</head>
<body>
  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/jqueryval")


  @using (Html.BeginForm())
  {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <h4>TipoIdentificacion</h4>
      <hr />
      @Html.HiddenFor(model => model.IdTipoIdentificacion)
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger", tabindex = 1 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          <div class="checkbox">
            @Html.DropDownListFor(model => model.Estado, new SelectList(ViewBag.ListaEstados, "Value", "Text"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 2 })
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
      </div>
    </div>
  }

  <div>
    @Html.ActionLink("Salir", "Index")
  </div>
</body>
</html>

Proyecto/Views/TipoIdentificacion/Index.cshtml
@model IEnumerable<Proyecto.Models.TipoIdentificacion>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>Index</title>
</head>
<body>
  <p>
    @Html.ActionLink("Nueva Tipo Identificacion", "Crear", "TipoIdentificacion", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-small btn-primary pull-left" })
  </p>
  <table class="table">
    <tr>
      <th>
        @Html.DisplayNameFor(model => model.IdTipoIdentificacion)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Descripcion)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Estado)
      </th>
      <th></th>
    </tr>

    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.IdTipoIdentificacion)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
          @if (item.Estado == true)
          {
            @Html.Label("Activo")

          }
          else
          {
            @Html.Label("Inactivo")
          }
        </td>
        <td>
          @Html.ActionLink("Editar", "Editar", new { id = item.IdTipoIdentificacion }, new { @class = "btn btn-success btn-sm" }) |
          @Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdTipoIdentificacion }, new { @class = "btn btn-danger btn-sm", onclick = "return Confirmar(this);" })
        </td>
      </tr>
    }
  </table>
</body>
</html>