Proyecto/Models/Estudiante.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto.Models
{
    public class Estudiante
    {
        public int IdEstudiante { get; set; }
        public int IdInstitucion { get; set; }
        public int IdUsuario { get; set; }
        public int IdGrado { get; set; }
        public bool Estado { get; set; }
    }
}

Proyecto/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using BLL;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    [Authorize]
    public class EstudianteController : Controller
    {
    clsDocente ObjDocente = new clsDocente();
    clsBitacora Objbitacora = new clsBitacora();
    [Authorize(Roles = "Administrador")]
    public ActionResult Index()
        {
            try
            {
                List<EstudianteList> listaEstudiante = new List<EstudianteList>();
                clsEstudiante Estuadiante = new clsEstudiante();
                var data = Estuadiante.ConsultarEstudianteLista().ToList();

                foreach (var item in data)
                {
                    EstudianteList modelo = new EstudianteList();
                    modelo.IdEstudiante = item.IdEstudiante;
                    modelo.Institucion = item.Institucion;
                    modelo.Cedula = item.Cedula;
                    modelo.Nombre = item.Nombre;
                    modelo.Grado = item.Grado;
                    modelo.Estado = item.Estado;
                    listaEstudiante.Add(modelo);
                }
                return View(listaEstudiante);
            }
            catch
            {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("EstudianteController", "Index", "Error en la consulta de los datos", 1, DateTime.UtcNow.Date, us);

        return RedirectToAction("Error", "Error");
            }
        }
    [Authorize(Roles = "Administrador")]
    public ActionResult Crear()
        {
            try
            {
                ViewBag.ListaInstitucion = CargarInstitucion();
                ViewBag.ListaUsuario = CargarUsuario();
                ViewBag.ListaGrado = CargarGrado();
                ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
                return View();
            }
            catch (Exception)
            {

                throw;
            }

        }
    [Authorize(Roles = "Administrador")]
    [HttpPost]
        public ActionResult Crear(Estudiante estudiante)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    clsEstudiante ObjEstudiante = new clsEstudiante();
                    bool Resultado = ObjEstudiante.AgregarEstudiante(estudiante.IdInstitucion, estudiante.IdUsuario, estudiante.IdGrado, estudiante.Estado);

                    if (Resultado)
                    {
            int us = Convert.ToInt32(Session["IdUsuario"].ToString());
            Objbitacora.AgregarBitacora("EstudianteController", "Crear", "Exito", 1, DateTime.UtcNow.Date, us);

            return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.ListaInstitucion = CargarInstitucion();
                        ViewBag.ListaUsuario = CargarUsuario();
                        ViewBag.ListaGrado = CargarGrado();
                        ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");

                        return View("Crear");
                    }
                }
                else
                {
                    ViewBag.ListaInstitucion = CargarInstitucion();
                    ViewBag.ListaUsuario = CargarUsuario();
                    ViewBag.ListaGrado = CargarGrado();
                    ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");

                    return View("Crear");
                }

            }
            catch
            {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("EstudianteController", "Crear", "Error en la creacion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
            }
        }
    [Authorize(Roles = "Administrador")]
    public ActionResult Editar(int id)
        {
            try
            {
                clsEstudiante ObjEstudiante = new clsEstudiante();
        ViewBag.ListaInstitucion = CargarInstitucion();
        ViewBag.ListaUsuario = CargarUsuario();
        ViewBag.ListaGrado = CargarGrado();
        ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
        var dato = ObjEstudiante.ConsultaEstudiante(id);

                Estudiante modelo = new Estudiante();
                modelo.IdEstudiante = dato.IdEstudiante;
                modelo.IdInstitucion = dato.IdInstitucion;
                modelo.IdUsuario = dato.IdUsuario;
                modelo.IdGrado = Convert.ToInt32(dato.IdGrado);
                modelo.Estado = dato.Estado;
                return View(modelo);
            }
            catch (Exception)
            {

                throw;
            }

        }
    [Authorize(Roles = "Administrador")]
    [HttpPost]
        public ActionResult Editar(int id, Estudiante estudiante)
        {
            try
            {

                clsEstudiante ObjEstudiante = new clsEstudiante();
                bool Resultado = ObjEstudiante.ActualizarEstudiante(id, estudiante.IdInstitucion, estudiante.IdUsuario, estudiante.IdGrado, estudiante.Estado);

                if (Resultado)
                {
          int us = Convert.ToInt32(Session["IdUsuario"].ToString());
          Objbitacora.AgregarBitacora("EstudianteController", "Editar", "Exito", 1, DateTime.UtcNow.Date, us);

          return RedirectToAction("Index");
                }
                else
                {

                    ViewBag.ListaInstitucion = CargarInstitucion();
                    ViewBag.ListaUsuario = CargarUsuario();
                    ViewBag.ListaGrado = CargarGrado();
                    ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
                    return View("Editar");
                }
            }
            catch
            {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("EstudianteController", "Editar", "Error en la edicion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
            }
        }
    [Authorize(Roles = "Administrador")]
    public ActionResult Eliminar(int id)
        {
            try
            {
                clsEstudiante ObjEstudiante = new clsEstudiante();
                bool Resultado = ObjEstudiante.EliminarEstudiante(id);

                if (Resultado)
                {
          int us = Convert.ToInt32(Session["IdUsuario"].ToString());
          Objbitacora.AgregarBitacora("EstudianteController", "Eliminar", "Exito", 1, DateTime.UtcNow.Date, us);

          return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch
            {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("EstudianteController", "Eliminar", "Error en la eliminacion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
            }
        }

    clsInstitucion Institucion = new clsInstitucion();
        clsUsuario Usuario = new clsUsuario();
        clsGrado Grado = new clsGrado();
        public List<ConsultarInstitucionResult> CargarInstitucion()
        {
            List<ConsultarInstitucionResult> instituciones = Institucion.ConsultarInstitucion();
            return instituciones;
        }

        public List<ConsultarUsuarioViewBagResult> CargarUsuario()
        {
            List<ConsultarUsuarioViewBagResult> usuario = Usuario.ConsultarUsuarioViewBag();
            return usuario;
        }

        public List<ConsultarGradoResult> CargarGrado()
        {
            List<ConsultarGradoResult> grado = Grado.ConsultarGrado();
            return grado;
        }
    }
}

Proyecto/Views/Estudiante/Crear.cshtml
@model Proyecto.Models.Estudiante

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Agregar un nuevo Estudiante</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Estudiante</h4>
        <hr />
        @Html.Hidden("IdEstudiante", 0)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.IdInstitucion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdInstitucion, new SelectList(ViewBag.ListaInstitucion, "IdInstitucion", "Descripcion"), "--Institucion--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 1 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdUsuario, new SelectList(ViewBag.ListaUsuario, "IdUsuario", "Nombre"), "--Usuario--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 2 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdGrado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdGrado, new SelectList(ViewBag.ListaGrado, "IdGrado", "Descripcion"), "--Grado--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 3 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.DropDownListFor(model => model.Estado, new SelectList(ViewBag.ListaEstados, "Value", "Text"), "--Estado--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 4 })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Regresar", "Index")
    </div>
</body>
</html>

Proyecto/Views/Estudiante/Editar.cshtml
@model Proyecto.Models.Estudiante

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Editar</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Estudiante</h4>
        <hr />
        @Html.HiddenFor(model => model.IdEstudiante)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })      
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdInstitucion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdInstitucion, new SelectList(ViewBag.ListaInstitucion, "IdInstitucion", "Descripcion"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 1 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdUsuario, new SelectList(ViewBag.ListaUsuario, "IdUsuario", "Nombre"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 2 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdGrado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdGrado, new SelectList(ViewBag.ListaGrado, "IdGrado", "Descripcion"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 3 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.DropDownListFor(model => model.Estado, new SelectList(ViewBag.ListaEstados, "Value", "Text"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 4 })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Regresar", "Index")
    </div>
</body>
</html>

Proyecto/Views/Estudiante/Index.cshtml
@model IEnumerable<Proyecto.Models.EstudianteList>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Nuevo Estudiante", "Crear", "Estudiante", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-small btn-primary pull-left" })
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdEstudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Institucion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEstudiante)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Institucion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cedula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grado)
                </td>
                <td>
                    @if (item.Estado == true)
                    {
                        @Html.Label("Activo")

                    }
                    else
                    {
                        @Html.Label("Inactivo")
                    }
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.IdEstudiante }, new { @class = "btn btn-success btn-sm" }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdEstudiante }, new { @class = "btn btn-danger btn-sm", onclick = "return Confirmar(this);" })
                </td>
            </tr>
        }
        <tfoot>
            <tr>
                <th><div class="panel-footer">Cantidad = @Model.Count()</div></th>
            </tr>
        </tfoot>
    </table>
</body>
</html>
@section Scripts
{
    <script type="text/javascript">
  $(document).ready(function () {
    $('#Datos').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
    </script>

}