Proyecto/Models/Institucion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto.Models
{
    public class Institucion
    {
        public int IdInstitucion { get; set; }
        public string Descripcion { get; set; }
        public string Telefono { get; set; }
        public string Encargado { get; set; }
        public string Direccion { get; set; }
        public char Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public bool Estado { get; set; }
    }
}

Proyecto/Controllers/InstitucionController.cs
using BLL;
using DAL;
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto.Controllers
{
    public class InstitucionController : Controller
    {
    clsBitacora Objbitacora = new clsBitacora();
    [Authorize(Roles = "Administrador")]
    public ActionResult Index()
    {
      try
      {
        List<Institucion> listaRol = new List<Institucion>();
        clsInstitucion Institucion = new clsInstitucion();
        var data = Institucion.ConsultarInstitucion().ToList();

        foreach (var item in data)
        {
          Institucion modelo = new Institucion();
          modelo.IdInstitucion = item.IdInstitucion;
          modelo.Descripcion = item.Descripcion;
          modelo.Telefono = item.Telefono;
          modelo.Encargado = item.Encargado;
          modelo.Direccion = item.Direccion;
          modelo.Provincia = item.Provincia;
          modelo.Canton = item.Canton;
          modelo.Distrito = item.Distrito;
          modelo.Estado = item.Estado;
          listaRol.Add(modelo);
        }
        return View(listaRol);
      }
      catch
      {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("InstitucionController", "Index", "Eror en la consulta de los datos", 1, DateTime.UtcNow.Date, us);

        return RedirectToAction("Error", "Error");
      }
    }
    [Authorize(Roles = "Administrador")]
    public ActionResult Crear()
    {
      try
      {
        ViewBag.ListaProvincias = CargaProvincias();
        ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
        return View();
      }
      catch (Exception)
      {

        throw;
      }

    }

    [Authorize(Roles = "Administrador")]
    [HttpPost]
    public ActionResult Crear(Institucion institucion)
    {
      try
      {
        if (ModelState.IsValid)
        {

          clsInstitucion Institucion = new clsInstitucion();
          bool Resultado = Institucion.AgregarInstitucion(institucion.Descripcion, institucion.Telefono, institucion.Encargado,
            institucion.Direccion, institucion.Provincia, institucion.Canton, institucion.Distrito, institucion.Estado);
          clsBitacora Objbitacora = new clsBitacora();

          if (Resultado)
          {
            int us = Convert.ToInt32(Session["IdUsuario"].ToString());
            Objbitacora.AgregarBitacora("InstitucionController", "Crear", "Exito", 1, DateTime.UtcNow.Date, us);

            return RedirectToAction("Index");
          }
          else
          {
            ViewBag.ListaProvincias = CargaProvincias();
            ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
            return View("Crear");
          }
        }
        else
        {
          ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
          return View("Crear");
        }

      }
      catch
      {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("InstitucionController", "Crear", "Error en creacion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
      }
    }
    [Authorize(Roles = "Administrador")]
    public ActionResult Editar(int id)
    {
      try
      {
        clsInstitucion Institucion = new clsInstitucion();
        ViewBag.ListaProvincias = CargaProvincias();
        ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
        var dato = Institucion.ConsultaInstitucion(id);

        Institucion modelo = new Institucion();
        modelo.IdInstitucion = dato.IdInstitucion;
        modelo.Descripcion = dato.Descripcion;
        modelo.Telefono = dato.Telefono;
        modelo.Encargado = dato.Encargado;
        modelo.Direccion = dato.Direccion;
        modelo.Provincia = dato.Provincia;
        modelo.Canton = dato.Canton;
        modelo.Distrito = dato.Distrito;
        modelo.Estado = dato.Estado;
        return View(modelo);
      }
      catch (Exception)
      {

        throw;
      }

    }
    [Authorize(Roles = "Administrador")]
    [HttpPost]
    public ActionResult Editar(int id, Institucion institucion)
    {
      try
      {
        clsInstitucion Institucion = new clsInstitucion();
        bool Resultado = Institucion.ActualizarInstitucion(id, institucion.Descripcion, institucion.Telefono, institucion.Encargado, institucion.Direccion, institucion.Provincia, institucion.Canton, institucion.Distrito, institucion.Estado);

        if (Resultado)
        {
          int us = Convert.ToInt32(Session["IdUsuario"].ToString());
          Objbitacora.AgregarBitacora("InstitucionController", "Editar", "Exito", 1, DateTime.UtcNow.Date, us);

          return RedirectToAction("Index");
        }
        else
        {
          ViewBag.ListaProvincias = CargaProvincias();
          ViewBag.ListaEstados = new SelectList(new[] {
                                   new SelectListItem { Value = "true", Text = "Activo" },
                                   new SelectListItem { Value = "false", Text = "Inactivo" }
                                                               }, "Value", "Text");
          return View("Editar");
        }
      }
      catch
      {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("InstitucionController", "Editar", "Error en la edicion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
      }
    }
    [Authorize(Roles = "Administrador")]
    public ActionResult Eliminar(int id)
    {
      try
      {
        clsInstitucion Institucion = new clsInstitucion();
        bool Resultado = Institucion.EliminarInstitucion(id);

        if (Resultado)
        {
          int us = Convert.ToInt32(Session["IdUsuario"].ToString());
          Objbitacora.AgregarBitacora("InstitucionController", "Eliminar", "Exito", 1, DateTime.UtcNow.Date, us);

          return RedirectToAction("Index");
        }
        else
        {
          return RedirectToAction("Index");
        }

      }
      catch
      {
        int us = Convert.ToInt32(Session["IdUsuario"].ToString());
        Objbitacora.AgregarBitacora("InstitucionController", "Eliminar", "Error en la eliminacion de los datos", 1, DateTime.UtcNow.Date, us);

        return View();
      }
    }
    clsInformacion Informacion = new clsInformacion();
    /// <summary>
    /// Obtiene Provincias
    /// </summary>
    /// <returns></returns>
    public List<ProvinciasResult> CargaProvincias()
    {
      List<ProvinciasResult> provincias = Informacion.ObtenerProvincias();
      return provincias;
    }
    /// <summary>
    /// Obtiene Cantones
    /// </summary>
    /// <param name="provincia"></param>
    /// <returns></returns>
    public List<CantonesResult> CargaCanton(char provincia)
    {
      List<CantonesResult> cantones = Informacion.ObtenerCantones(provincia);
      return cantones;
    }
    /// <summary>
    /// Obtiene Distritos
    /// </summary>
    /// <param name="provincia"></param>
    /// <param name="canton"></param>
    /// <returns></returns>
    public List<DistritosResult> CargaDistrito(char provincia, string canton)
    {
      List<DistritosResult> distritos = Informacion.ObtenerDistritos(provincia, canton);
      return distritos;
    }
    /// <summary>
    /// Cargar Cantones hacia la pantalla
    /// </summary>
    /// <param name="provincia"></param>
    /// <returns></returns>
    [HttpPost]
    public JsonResult CargaCantones(char provincia)
    {
      List<CantonesResult> cantones = Informacion.ObtenerCantones(provincia);
      return Json(cantones, JsonRequestBehavior.AllowGet);
    }
    /// <summary>
    /// Cargar Disttritos hacia la pantalla
    /// </summary>
    /// <param name="provincia"></param>
    /// <param name="canton"></param>
    /// <returns></returns>
    [HttpPost]
    public JsonResult CargaDistritos(char provincia, string canton)
    {
      List<DistritosResult> distritos = Informacion.ObtenerDistritos(provincia, canton);
      return Json(distritos, JsonRequestBehavior.AllowGet);
    }
  }
}

Proyecto/Views/Institucion/Crear.cshtml
@model Proyecto.Models.Institucion

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
  <meta name="viewport" content="width=device-width" />
  <title>Crear</title>
</head>
<body>
  @using (Html.BeginForm())
  {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <h4>Institucion</h4>
      <hr />
      @Html.Hidden("IdInstitucion", 0)
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })


      <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger", tabindex = 1})
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger", tabindex = 2})
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Encargado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Encargado, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Encargado, "", new { @class = "text-danger", tabindex = 3 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger", tabindex = 4})
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownListFor(model => model.Provincia, new SelectList(ViewBag.ListaProvincias, "Provincia", "Nombre"), "--Provincia--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 5 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Canton, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownListFor(model => model.Canton, new SelectList(string.Empty, "Canton", "Nombre"), "--Canton--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 6 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownListFor(model => model.Distrito, new SelectList(string.Empty, "Distrito", "Nombre"), "--Distrito--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 7 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          <div class="checkbox">
            @Html.DropDownListFor(model => model.Estado, new SelectList(ViewBag.ListaEstados, "Value", "Text"), "--Estado--", new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 8 })
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <input type="submit" value="Crear" class="btn btn-default" />
        </div>
      </div>
    </div>
  }

  <div>
    @Html.ActionLink("Salir", "Index")
  </div>
</body>
</html>
@section Scripts
{

  <script type="text/javascript">
        $(document).ready(function () {
            $("#Provincia").change(function () {
                $("#Canton").empty();
                $("#Distrito").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("CargaCantones")',
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    data: JSON.stringify({ provincia: $("#Provincia").val() }),
                    success: function (cantones) {
                        $("#Canton").append("<option value=''>--Seleccione--</option>");
                        $.each(cantones, function (i, canton) {
                            $("#Canton").append('<option value="' + canton.Canton + '">' + canton.Nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Fallo al cargar los cantones : ' + ex);
                    }
                });
            })
            $("#Canton").change(function () {
                $("#Distrito").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("CargaDistritos")',
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    data: JSON.stringify({ provincia: $("#Provincia").val(), canton: $("#Canton").val() }),
                    success: function (distritos) {
                        $("#Distrito").append("<option value=''>--Seleccione--</option>");
                        $.each(distritos, function (i, distrito) {
                            $("#Distrito").append('<option value="' + distrito.Distrito + '">' + distrito.Nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Fallo al cargar los distritos : ' + ex);
                    }
                });
            })

        });
  </script>
}

Proyecto/Views/Institucion/Editar.cshtml
@model Proyecto.Models.Institucion

@{
  Layout = "~/Views/Shared/_Layout.cshtml";
}
}

<!DOCTYPE html>

<html>
<head>
  <meta name="viewport" content="width=device-width" />
  <title>Editar</title>
</head>
<body>
  @using (Html.BeginForm())
  {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <h4>Institucion</h4>
      <hr />
      @Html.HiddenFor(model => model.IdInstitucion)
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger", tabindex = 1 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger", tabindex = 2 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Encargado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Encargado, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Encargado, "", new { @class = "text-danger", tabindex = 3 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger", tabindex = 4 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownListFor(model => model.Provincia, new SelectList(ViewBag.ListaProvincias, "Provincia", "Nombre"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 5 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Canton, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownListFor(model => model.Canton, new SelectList(string.Empty, "Canton", "Nombre"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 6 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownListFor(model => model.Distrito, new SelectList(string.Empty, "Distrito", "Nombre"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 7 })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownListFor(model => model.Estado, new SelectList(ViewBag.ListaEstados, "Value", "Text"), new { @class = "form-control", style = "font-size: 1.3em; font-weight:700;", tabindex = 8 })
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
      </div>
    </div>
  }

  <div>
    @Html.ActionLink("Salir", "Index")
  </div>
</body>
</html>
@section Scripts
{

  <script type="text/javascript">
        $(document).ready(function () {
            $("#Provincia").change(function () {
                $("#Canton").empty();
                $("#Distrito").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("CargaCantones")',
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    data: JSON.stringify({ provincia: $("#Provincia").val() }),
                    success: function (cantones) {
                        $("#Canton").append("<option value=''>--Seleccione--</option>");
                        $.each(cantones, function (i, canton) {
                            $("#Canton").append('<option value="' + canton.Canton + '">' + canton.Nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Fallo al cargar los cantones : ' + ex);
                    }
                });
            })
            $("#Canton").change(function () {
                $("#Distrito").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("CargaDistritos")',
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    data: JSON.stringify({ provincia: $("#Provincia").val(), canton: $("#Canton").val() }),
                    success: function (distritos) {
                        $("#Distrito").append("<option value=''>--Seleccione--</option>");
                        $.each(distritos, function (i, distrito) {
                            $("#Distrito").append('<option value="' + distrito.Distrito + '">' + distrito.Nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Fallo al cargar los distritos : ' + ex);
                    }
                });
            })

        });
  </script>
}

Proyecto/Views/Institucion/Index.cshtml
@model IEnumerable<Proyecto.Models.Institucion>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
  <p>
    @Html.ActionLink("Nueva Institucion", "Crear", "Institucion", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-small btn-primary pull-left" })
  </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdInstitucion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Encargado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Provincia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Canton)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Distrito)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.IdInstitucion)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Descripcion)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Telefono)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Encargado)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Direccion)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Provincia)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Canton)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Distrito)
      </td>
      <td>
        @if (item.Estado == true)
        {
          @Html.Label("Activo")

        }
        else
        {
          @Html.Label("Inactivo")
        }
      </td>
      <td>
        @Html.ActionLink("Editar", "Editar", new { id = item.IdInstitucion }, new { @class = "btn btn-success btn-sm" }) |
        @Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdInstitucion }, new { @class = "btn btn-danger btn-sm", onclick = "return Confirmar(this);" })
      </td>
    </tr>
    }
    
    </table>
</body>
</html>